#ifndef NAVIGATION_STRUCTS_H
#define NAVIGATION_STRUCTS_H

enum NAVIGATION_STATE{
    NAV_IDLE,
    NAV_RESET,
    NAV_INITIALIZATION,
    NAV_STATIC_TUNING,
    NAV_DYNAMIC_TUNING, // implement when 9 DOF is available
    NAV_NOMINAL,
    NAV_AUGMENTED_NOMINAL,
};


#endif